TRAIN='train'
TEST='test'
NO_ARGUMENT_ERROR_MSG='Usage main.py <dataset_path> <train/test>'
DATASET_PATH_NOT_EXISTS_ERROR_MSG='Invalid dataset path'
SAVED_MODELS_FOLDER_PATH = './saved_models'
SAVED_MODEL_NAME = 'colorize_model'